version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home_-_particles
  timestamp: 1666521226
layout:
  top: {  }
  /navigation/: {  }
  /slideshow/:
    -
      - slideshow-2818
    -
      - social-9062
  /header/: {  }
  /above/:
    -
      - custom-2183
  /feature/:
    -
      - 'spacer-6159 15'
      - 'simplecontent-9547 70'
      - 'spacer-5541 15'
  /showcase/: {  }
  /utility/: {  }
  /container-main/:
    -
      -
        'sidebar 20': {  }
      -
        'mainbar 60':
          -
            - system-content-1179
      -
        'aside 20': {  }
  /expanded/: {  }
  /extension/: {  }
  /bottom/: {  }
  /container-footer/:
    -
      -
        /footer/:
          -
            - video-4150
          -
            - 'video-9333 33.3'
            - 'custom-6387 33.3'
            - 'video-9336 33.3'
        copyright: {  }
  offcanvas: {  }
structure:
  top:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  navigation:
    type: section
    attributes:
      boxed: '3'
      class: ''
      variations: ''
    inherit:
      outline: default
      include:
        - children
  slideshow:
    type: section
    attributes:
      boxed: ''
      class: fp-slideshow
      variations: ''
  header:
    attributes:
      boxed: ''
      class: fp-header
      variations: ''
  above:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: 'section-horizontal-paddings section-vertical-paddings'
  feature:
    type: section
    attributes:
      boxed: ''
      class: promo
      variations: ''
  showcase:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: 'section-horizontal-paddings section-vertical-paddings'
  utility:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: 'section-vertical-paddings section-horizontal-paddings'
  sidebar:
    type: section
    subtype: aside
    attributes:
      class: ''
      variations: ''
  mainbar:
    type: section
    subtype: main
    title: Main
    attributes:
      class: ''
      variations: section-horizontal-paddings
  aside:
    attributes:
      class: ''
      variations: ''
  container-main:
    attributes:
      boxed: ''
      class: ''
      extra: {  }
  expanded:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: 'section-vertical-paddings section-horizontal-paddings'
  extension:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: 'section-horizontal-paddings section-vertical-paddings nopaddingbottom'
  bottom:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: section-horizontal-paddings
  footer:
    attributes:
      boxed: ''
      class: 'section-horizontal-paddings section-vertical-paddings medpaddingbottom'
      variations: nopaddingtop
    block:
      variations: center
  copyright:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  container-footer:
    attributes:
      boxed: ''
      class: ''
      extra: {  }
  offcanvas:
    inherit:
      outline: '21'
      include:
        - attributes
        - block
        - children
content:
  slideshow-2818:
    title: Слайд
    attributes:
      source: particle
      height: 85vh
      heightMobile: 500px
      direction: horizontal
      bullets: enabled
      arrows: enabled
      autoplay: enabled
      autoplayTimeout: '8000'
      loop: enabled
      speed: '800'
      touchmove: enabled
      effect: flip
      items:
        -
          class: ''
          image: 'gantry-media://abiturientu/кск.jpg'
          main_title: 'Компьютерные системы и комплексы'
          description1: ''
          description2: ''
          link: /index.php/abiturientu/spetsialnosti/kompyuternye-sistemy-i-kompleksy
          linktarget: _self
          title: 'Новый пункт'
        -
          class: ''
          image: 'gantry-media://abiturientu/3.jpg'
          main_title: 'Сварщик ручной и частично механизированной сварки'
          description1: ''
          description2: ''
          link: /index.php/abiturientu/professii/15-01-05-svarshchik-ruchnoj-i-chastichno-mekhanizirovannoj-svarki-naplavki
          linktarget: _self
          title: 'Новый пункт'
        -
          class: ''
          image: 'gantry-media://abiturientu/5.jpg'
          main_title: 'Повар, кондитер'
          description1: ''
          description2: ''
          link: /index.php/abiturientu/professii/43-01-09-povar-konditer
          linktarget: _self
          title: 'Новый пункт'
        -
          class: ''
          image: 'gantry-media://abiturientu/7.jpg'
          main_title: 'Электромонтер по ремонту и обслуживанию электрооборудования'
          description1: ''
          description2: ''
          link: /index.php/abiturientu/professii/13-01-10-elektromonter-po-remontu-i-obsluzhivaniyu-elektrooborudovaniya-po-otraslyam
          linktarget: _self
          title: 'Новый пункт'
        -
          class: ''
          image: 'gantry-media://abiturientu/2.jpg'
          main_title: 'Экономика и бухгалтерский учет'
          description1: ''
          description2: ''
          link: /index.php/abiturientu/spetsialnosti/ekonomika-i-bukhgalterskij-uchet-po-otraslyam
          linktarget: _self
          title: 'Новый пункт'
        -
          class: ''
          image: 'gantry-media://abiturientu/4.jpg'
          main_title: 'Мастер общестроительных работ'
          description1: ''
          description2: ''
          link: /index.php/abiturientu/professii/08-01-07-master-obshchestroitelnykh-rabot
          linktarget: _self
          title: 'New item'
        -
          class: ''
          image: 'gantry-media://abiturientu/6.jpg'
          main_title: 'Продавец, контролер-кассир'
          description1: ''
          description2: ''
          link: /index.php/abiturientu/professii/prodavets-kontroler-kassir
          linktarget: _self
          title: 'New item'
        -
          class: ''
          image: 'gantry-media://abiturientu/8.jpg'
          main_title: 'Мастер контрольно-измерительных приборов и автоматики'
          description1: ''
          description2: ''
          link: /index.php/abiturientu/professii/15-01-31-master-kontrolno-izmeritelnykh-priborov-i-avtomatiki
          linktarget: _self
          title: 'New item'
      article:
        filter:
          categories: ''
          articles: ''
          featured: include
        limit:
          total: '5'
          start: '0'
        sort:
          orderby: publish_up
          ordering: ASC
        display:
          image:
            enabled: intro
          author:
            enabled: show
          author_image:
            enabled: intro
          text:
            type: intro
            limit: ''
          title:
            enabled: show
            limit: ''
          link:
            enabled: enabled
            target: _self
    block:
      variations: 'nomargintop nomarginbottom nopaddingbottom nopaddingtop'
  social-9062:
    block:
      variations: center
  custom-2183:
    title: 'Custom HTML'
    attributes:
      html: "<p align=\"center\"><em><strong>Уважаемые абитуриенты</strong></em></p>\n<p align=\"left\"><img style=\"float: left; margin: 25px;\" title=\"и.о. директора Сальского индустриального техникума Якимова Т. В.\" src=\"https://sit-salsk.ru/wp-content/uploads/2022/10/Якимова-Татьяна-Владимировна-зам.-дир.-по-учебной-работе-копия.jpg\" width=\"40%\" />Государственное бюджетное профессиональное образовательное учреждение Ростовской области «Сальский индустриальный техникум» является современным образовательным учреждением, успешно готовящим кадры среднего звена для развивающейся экономики Донского края.<br />Техникум молод — в 2023 году он отметит своё 45-летие — и он динамичен, способен быстро реагировать на изменения требований законодательства, запросов экономики региона и рынка труда.<br />За эти годы он прошел путь от филиала Краснодарского станкостроительного техникума до самостоятельного учреждения, являющегося одним из лучших в отрасли.<br />Образовательные программы, реализуемые в техникуме, соответствуют приоритетным направлениям технологического развития экономики и производства: автоматизация и роботизация, IT-технологии, экономика и управление предприятием.</p>\n<p align=\"left\">Коллектив техникума постоянно работает над повышением уровня образовательного процесса, совершенствованием всего учебно-программного комплекса, над повышением качества подготовки молодых специалистов.</p>\n<p align=\"left\">Из года в год укрепляется учебно-материальная база, повышается профессиональный уровень преподавательского и учебно-вспомогательного персонала.</p>\n<p align=\"left\">Сегодня 50% преподавателей имеют высшую квалификационную категорию и 33% — первую. Преподавательский состав техникума весьма молод — средний возраст составляет около 40 лет. Это — сплав зрелости и профессионального опыта. Ежегодно наши ряды пополняются молодыми специалистами — творческими и инициативными. Наши педагоги принимают самое активное участие в конкурсах педагогического мастерства различных уровней — от территориального до регионального и Всероссийского — и всегда достойно представляют наш коллектив, демонстрируя высокий уровень профессионализма.</p>\n<p align=\"left\">На базе техникума также проводятся мероприятия областного и территориального значения.</p>\n<p align=\"left\">Сальский индустриальный техникум сегодня — это качественное образование и организация учебного процесса с использованием современных образовательных технологий, комфортабельные учебные аудитории, оснащенные высокотехнологичным лабораторным оборудованием.</p>\n<p align=\"left\">Это также доброжелательная творческая атмосфера, создающая оптимальные условия для развития творческого потенциала студентов, и интересная студенческая жизнь. Наши студенты активно занимаются спортом, художественным и техническим творчеством. Работает команда КВН «Новое поколение», студенческое самоуправление, развито волонтерское движение. Наши ребята становятся победителями и призерами территориальных и областных конкурсов профессионального мастерства, о чем всегда оперативно информирует посетителей сайта «Лента новостей».</p>\n<p align=\"left\">В коллективе в течение многих лет сложилась обстановка строгого контроля и ответственности за порученное дело, нетерпимости к халатному отношению к учебе, нарушениям Устава техникума и правил внутреннего распорядка, к проявлениям бескультурья и невежества.</p>\n<p align=\"left\">Всё это вместе позволяет давать качественное профессиональное образование, создает престиж и неповторимый образ нашему техникуму, а выпускникам дает уверенность в трудоустройстве и успешной карьере.</p>\n<p align=\"left\">Молодость — самая прекрасная пора в жизни человека. Поэтому, обращаясь к молодежи, нашим студентам и выпускникам школ, хочу сказать: максимально используйте это время для своего профессионального роста и духовного развития своей личности, дерзайте — и вы достигнете самых высоких жизненных вершин.</p>"
  spacer-6159:
    inherit:
      outline: '21'
      include:
        - attributes
        - block
      particle: spacer-8015
  simplecontent-9547:
    title: 'Simple Content'
    attributes:
      class: ''
      title: ''
      items:
        -
          layout: header
          created_date: ''
          content_title: 'История техникума'
          author: ''
          leading_content: ''
          main_content: "История Сальского индустриального техникума тесно связана с развитием Сальского завода Кузнечно-прессового оборудования (КПО). Стране нужны были специалисты: технологи, конструкторы, мастера, начальники цехов, токари, фрезеровщики, слесаря, шлифовщики.<br>\nС 1993 года по Приказу №123 от 25 марта министра образования Сальский станкостроительный техникум переименован в Сальский индустриальный техникум. С этого года работают факультеты по специальностям: – «Мастер контрольно измерительных приборов и автоматики» – «Юрист-бухгалтер-правовед» – «Экономика, бухгалтерский учёт и контроль по отраслям» – Электромонтер по ремонту и обслуживанию электрооборудования» – «Компьютерные системы и комплексы»."
          readmore_label: 'ГБПОУ РО "СИТ"'
          readmore_link: 'https://sit-salsk.ru/'
          readmore_class: ''
          readmore_target: _blank
          title: Gantry
    block:
      variations: 'nomarginall nopaddingall'
  spacer-5541:
    inherit:
      outline: '21'
      include:
        - attributes
        - block
      particle: spacer-6523
  video-4150:
    attributes:
      class: ''
      title: ''
      columns: '1'
      items:
        -
          caption: ''
          source: youtube
          video: 'https://www.youtube.com/watch?v=2g_wxvZq2WA'
          local: {  }
          posterimage: ''
          loop: enabled
          autoplay: disabled
          controls: enabled
          info: disabled
          related: disabled
          muted: enabled
          start: ''
          title: 'New item'
  video-9333:
    attributes:
      class: ''
      title: ''
      columns: '1'
      items:
        -
          caption: ''
          source: youtube
          video: 'https://www.youtube.com/watch?v=Q7VtrHboWyc'
          local: {  }
          posterimage: ''
          loop: enabled
          autoplay: disabled
          controls: enabled
          info: disabled
          related: disabled
          muted: enabled
          start: ''
          title: 'New item'
  custom-6387:
    title: 'Custom HTML'
    attributes:
      html: '<H2>Презентация профориентации</h2><iframe src="https://onedrive.live.com/embed?cid=9D9B73866FEF0B86&resid=9D9B73866FEF0B86%21119&authkey=AJ2ddoos_LA4CoY&em=2" height="205"  frameborder="1" scrolling="no"></iframe>'
    block:
      variations: center
  video-9336:
    attributes:
      class: ''
      title: ''
      columns: '1'
      items:
        -
          caption: ''
          source: youtube
          video: 'https://www.youtube.com/watch?v=bOUzJezOvsY'
          local: {  }
          posterimage: ''
          loop: enabled
          autoplay: disabled
          controls: enabled
          info: disabled
          related: disabled
          muted: enabled
          start: ''
          title: 'New item'
