name: 26
timestamp: 1728137135
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1666521226
positions:
  above-a: 'Above A'
  above-b: 'Module Position'
  mainbar-a: 'MainBar A'
  A1: 'Module Position'
  A2: 'Module Position'
  A3: 'Module Position'
  poisk: 'Module Position'
  slideshow-a: 'Slideshow A'
  header-a: 'Header A'
  feature-a: 'Feature A'
  showcase-a: 'Showcase A'
  utility-a: 'Utility A'
  sidebar-a: 'Sidebar A'
  aside-a: 'Aside A'
  expanded-a: 'Expanded A'
  extension-a: 'Extension A'
  bottom-a: 'Bottom A'
  footer-a: 'Module Position'
  '00': 'Module Position'
  '01': 'Module Position'
  '02': 'Module Position'
  '03': 'Module Position'
  '04': 'Module Position'
  '05': 'Module Position'
  '06': 'Module Position'
  '07': 'Module Position'
  '08': 'Module Position'
  'МДК 03.02_3': 'Module Position'
  'МДК 03.02_4': 'Module Position'
  ПР_МДК02_01_КИП4: 'Module Position'
  '09': 'Module Position'
  '010': 'Module Position'
  '011': 'Module Position'
  '012': 'Module Position'
  '014': 'Module Position'
  '015': 'Module Position'
  0: 'Module Position'
  1: 'Module Position'
  2: 'Module Position'
  3: 'Module Position'
  4: 'Module Position'
  5: 'Module Position'
  6: 'Module Position'
  7: 'Module Position'
  8: 'Module Position'
  9: 'Module Position'
  22: 'Module Position'
  10: 'Module Position'
  11: 'Module Position'
  12: 'Module Position'
  13: 'Module Position'
  14: 'Module Position'
  15: 'Module Position'
  16: 'Module Position'
  17: 'Module Position'
  18: 'Module Position'
sections:
  top: Top
  navigation: Navigation
  slideshow: Slideshow
  above: Above
  feature: Feature
  showcase: Showcase
  utility: Utility
  expanded: Expanded
  extension: Extension
  bottom: Bottom
  copyright: Copyright
  header: Header
  sidebar: Sidebar
  aside: Aside
  mainbar: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  position:
    position-position-5497: 'Above A'
    position-position-2430: 'Module Position'
    position-position-5843: 'MainBar A'
    position-position-9035: 'Module Position'
    position-position-4454: 'Module Position'
    position-position-4061: 'Module Position'
    position-position-4607: 'Module Position'
    position-position-5249: 'Slideshow A'
    position-position-4503: 'Header A'
    position-position-8470: 'Feature A'
    position-position-7469: 'Showcase A'
    position-position-4214: 'Utility A'
    position-position-4239: 'Sidebar A'
    position-position-8160: 'Aside A'
    position-position-5862: 'Expanded A'
    position-position-5645: 'Extension A'
    position-position-5370: 'Bottom A'
    position-position-5663: 'Module Position'
    position-position-9344: 'Module Position'
    position-position-1298: 'Module Position'
    position-position-1411: 'Module Position'
    position-position-8680: 'Module Position'
    position-position-6066: 'Module Position'
    position-position-7445: 'Module Position'
    position-position-8868: 'Module Position'
    position-position-4216: 'Module Position'
    position-position-6113: 'Module Position'
    position-position-3161: 'Module Position'
    position-position-2789: 'Module Position'
    position-position-2065: 'Module Position'
    position-position-8838: 'Module Position'
    position-position-7895: 'Module Position'
    position-position-6493: 'Module Position'
    position-position-7551: 'Module Position'
    position-position-9844: 'Module Position'
    position-position-5783: 'Module Position'
    position-position-5817: 'Module Position'
    position-position-1237: 'Module Position'
    position-position-1310: 'Module Position'
    position-position-9583: 'Module Position'
    position-position-1213: 'Module Position'
    position-position-8787: 'Module Position'
    position-position-8678: 'Module Position'
    position-position-1275: 'Module Position'
    position-position-3911: 'Module Position'
    position-position-6648: 'Module Position'
    position-position-7294: 'Module Position'
    position-position-9374: 'Module Position'
    position-position-3585: 'Module Position'
    position-position-1519: 'Module Position'
    position-position-5809: 'Module Position'
    position-position-9065: 'Module Position'
    position-position-2351: 'Module Position'
    position-position-1906: 'Module Position'
    position-position-4937: 'Module Position'
    position-position-7198: 'Module Position'
  content:
    system-content-7737: 'Page Content'
  messages:
    system-messages-7190: 'System Messages'
  menu:
    menu-2267: Menu
  social:
    social-2711: Social
  custom:
    custom-6854: 'Custom HTML'
  copyright:
    copyright-7007: Copyright
  mobile-menu:
    mobile-menu-3262: 'Mobile Menu'
inherit:
  default:
    top: top
    navigation: navigation
    slideshow: slideshow
    header: header
    position-position-5497: position-position-3264
    position-position-2430: position-position-4979
    feature: feature
    showcase: showcase
    utility: utility
    sidebar: sidebar
    position-position-5843: position-position-8547
    position-position-9035: position-position-2010
    position-position-4454: position-position-6591
    position-position-4061: position-position-5336
    system-content-7737: system-content-1120
    aside: aside
    expanded: expanded
    extension: extension
    bottom: bottom
    footer: footer
    copyright: copyright
    offcanvas: offcanvas
    system-messages-7190: system-messages-9828
    position-position-4607: position-position-5716
    menu-2267: menu-2872
    position-position-5249: position-position-6661
    position-position-4503: position-position-7051
    position-position-8470: position-position-7980
    position-position-7469: position-position-9435
    position-position-4214: position-position-5239
    position-position-4239: position-position-9414
    position-position-8160: position-position-8807
    position-position-5862: position-position-8124
    position-position-5645: position-position-4800
    position-position-5370: position-position-3343
    position-position-5663: position-position-1848
    position-position-9344: position-position-2446
    position-position-1298: position-position-1945
    position-position-1411: position-position-2546
    position-position-8680: position-position-8551
    position-position-6066: position-position-8646
    position-position-7445: position-position-5856
    position-position-8868: position-position-1880
    position-position-4216: position-position-2121
    position-position-6113: position-position-9550
    position-position-3161: position-position-8269
    position-position-2789: position-position-5323
    position-position-2065: position-position-4518
    position-position-8838: position-position-3262
    position-position-7895: position-position-3379
    position-position-6493: position-position-9597
    position-position-7551: position-position-5988
    position-position-9844: position-position-2490
    position-position-5783: position-position-3914
    position-position-5817: position-position-3950
    position-position-1237: position-position-7016
    position-position-1310: position-position-9518
    position-position-9583: position-position-2022
    position-position-1213: position-position-3811
    position-position-8787: position-position-9911
    position-position-8678: position-position-8849
    position-position-1275: position-position-1429
    position-position-3911: position-position-8491
    position-position-6648: position-position-3009
    position-position-7294: position-position-5226
    position-position-9374: position-position-7954
    position-position-3585: position-position-7697
    position-position-1519: position-position-6851
    position-position-5809: position-position-5674
    position-position-9065: position-position-1691
    position-position-2351: position-position-3652
    position-position-1906: position-position-3316
    position-position-4937: position-position-3738
    position-position-7198: position-position-4078
    social-2711: social-8176
    custom-6854: custom-7038
    copyright-7007: copyright-6444
    mobile-menu-3262: mobile-menu-2576
