version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1666521226
layout:
  top: {  }
  navigation: {  }
  slideshow: {  }
  header: {  }
  /above/:
    -
      - position-position-5497
    -
      - position-position-2430
  feature: {  }
  showcase: {  }
  utility: {  }
  /container-main/:
    -
      -
        'sidebar 20': {  }
      -
        'mainbar 60':
          -
            - position-position-5843
          -
            - 'position-position-9035 33.3'
            - 'position-position-4454 33.3'
            - 'position-position-4061 33.3'
          -
            - system-content-7737
      -
        'aside 20': {  }
  expanded: {  }
  extension: {  }
  bottom: {  }
  /container-footer/:
    -
      -
        footer: {  }
        copyright: {  }
  offcanvas: {  }
structure:
  top:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  navigation:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  slideshow:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  header:
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  above:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: section-horizontal-paddings
  feature:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  showcase:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  utility:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  sidebar:
    type: section
    subtype: aside
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  mainbar:
    type: section
    subtype: main
    title: Main
    attributes:
      class: ''
      variations: section-horizontal-paddings
  aside:
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  container-main:
    attributes:
      boxed: ''
      class: ''
      extra: {  }
  expanded:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  extension:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  bottom:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  footer:
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  copyright:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  container-footer:
    attributes:
      boxed: ''
      class: ''
      extra: {  }
  offcanvas:
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
content:
  position-position-5497:
    title: 'Above A'
    inherit:
      outline: default
      include:
        - attributes
        - block
      particle: position-position-3264
  position-position-2430:
    title: 'Module Position'
    inherit:
      outline: default
      include:
        - attributes
        - block
      particle: position-position-4979
  position-position-5843:
    title: 'MainBar A'
    inherit:
      outline: default
      include:
        - attributes
        - block
      particle: position-position-8547
  position-position-9035:
    title: 'Module Position'
    inherit:
      outline: default
      include:
        - attributes
        - block
      particle: position-position-2010
  position-position-4454:
    title: 'Module Position'
    inherit:
      outline: default
      include:
        - attributes
        - block
      particle: position-position-6591
  position-position-4061:
    title: 'Module Position'
    inherit:
      outline: default
      include:
        - attributes
        - block
      particle: position-position-5336
  system-content-7737:
    inherit:
      outline: default
      include:
        - attributes
        - block
      particle: system-content-1120
