version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home_-_particles
  timestamp: 1666521226
layout:
  top: {  }
  /navigation/: {  }
  /slideshow/:
    -
      - slideshow-4169
    -
      - social-2632
    -
      - video-3605
  /header/:
    -
      - 'quickmenu-1783 50'
      - 'image-8214 50'
    -
      - position-module-8274
  /above/:
    -
      - locations-3441
  /feature/:
    -
      - 'spacer-8015 15'
      - 'simplecontent-5255 69.9'
      - 'spacer-6523 15'
  /showcase/: {  }
  /utility/: {  }
  /container-main/:
    -
      -
        'sidebar 20': {  }
      -
        'mainbar 60':
          -
            - system-content-1120
      -
        'aside 20': {  }
  /expanded/: {  }
  /extension/:
    -
      - flipster-1723
  /bottom/: {  }
  /container-footer/:
    -
      -
        /footer/: {  }
        copyright: {  }
  offcanvas:
    -
      - mobile-menu-2576
structure:
  top:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  navigation:
    type: section
    attributes:
      boxed: '3'
      class: ''
      variations: ''
    inherit:
      outline: default
      include:
        - children
  slideshow:
    type: section
    attributes:
      boxed: ''
      class: fp-slideshow
      variations: ''
  header:
    attributes:
      boxed: ''
      class: fp-header
      variations: ''
  above:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: 'section-horizontal-paddings section-vertical-paddings'
  feature:
    type: section
    attributes:
      boxed: ''
      class: promo
      variations: ''
  showcase:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: 'section-horizontal-paddings section-vertical-paddings'
  utility:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: 'section-vertical-paddings section-horizontal-paddings'
  sidebar:
    type: section
    subtype: aside
    attributes:
      class: ''
  mainbar:
    type: section
    subtype: main
    title: Main
    attributes:
      class: ''
      variations: section-horizontal-paddings
  aside:
    attributes:
      class: ''
  container-main:
    attributes:
      boxed: ''
      class: ''
      extra: {  }
  expanded:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: 'section-vertical-paddings section-horizontal-paddings'
  extension:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: 'section-horizontal-paddings section-vertical-paddings nopaddingbottom'
  bottom:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: section-horizontal-paddings
  footer:
    attributes:
      boxed: ''
      class: 'section-horizontal-paddings section-vertical-paddings medpaddingbottom'
      variations: nopaddingtop
    inherit:
      outline: default
      include:
        - block
        - children
  copyright:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  container-footer:
    attributes:
      boxed: ''
      class: ''
      extra: {  }
  offcanvas:
    attributes:
      swipe: '0'
content:
  slideshow-4169:
    title: Слайд
    attributes:
      source: particle
      height: 85vh
      heightMobile: 500px
      direction: horizontal
      bullets: enabled
      arrows: enabled
      autoplay: enabled
      autoplayTimeout: '8000'
      loop: enabled
      speed: '800'
      touchmove: enabled
      effect: flip
      items:
        -
          class: ''
          image: 'gantry-media://new_foto/a24.jpeg'
          main_title: '<div data-aos="fade-right"><span>Бардаков Дмитрий Николаевич</span></div>'
          description1: "<div data-aos=\"fade-right\"><span>Преподаватель\nвысшей категории<br></span></div>"
          description2: '<div data-aos="fade-left"><span><a href="https://sit-salsk.ru" target="_blank">Сальского индустриального техникума</a></span></div>'
          link: /index.php/obo-mne/dostizheniya
          linktarget: _blank
          title: я
        -
          class: ''
          image: 'gantry-media://new_foto/3b66199b-bacc-4ef1-a576-808ce90b0711.jpg'
          main_title: '<span>ВОСПИТАНИЕ - ВАЖНО</span>'
          description1: ''
          description2: "<span>И воспитание, и образование нераздельны.  Нельзя воспитывать, не передавая знания, \n всякое же знание действует воспитательно</span>"
          link: /index.php/vospitanie
          linktarget: _self
          title: Воспитание
        -
          class: ''
          image: 'gantry-media://home/6e77cfa3-abff-4c04-bba9-56fafdc3e556.jpg'
          main_title: '<span>Обучение</span>'
          description1: ''
          description2: "<span>2017 год - работа в \"Сальском индустриальном техникуме\".  Преподаю технические дисциплины  \n <a title=\"ПМ02\" href=\"http://пм02.рф/\" target=\"_blank\" rel=\"noopener\">учебный веб-ресурс</a></span>"
          link: /index.php/obuchenie
          linktarget: _self
          title: Обучение
      article:
        filter:
          categories: ''
          articles: ''
          featured: include
        limit:
          total: '5'
          start: '0'
        sort:
          orderby: publish_up
          ordering: ASC
        display:
          image:
            enabled: intro
          author:
            enabled: show
          author_image:
            enabled: intro
          text:
            type: intro
            limit: ''
          title:
            enabled: show
            limit: ''
          link:
            enabled: enabled
            target: _self
    block:
      variations: 'nomargintop nomarginbottom nopaddingbottom nopaddingtop'
  social-2632:
    block:
      variations: center
  video-3605:
    attributes:
      class: ''
      title: ''
      columns: '1'
      items:
        -
          caption: ''
          source: local
          video: ''
          local:
            -
              file: 'gantry-media://Animation/Бардаков_самопризентация.mp4'
              title: 'New item'
          posterimage: 'gantry-media://Animation/видео среднее качество.mp4_snapshot_00.18.351.jpg'
          loop: enabled
          autoplay: disabled
          controls: enabled
          info: disabled
          related: disabled
          muted: enabled
          start: ''
          title: 'New item'
  quickmenu-1783:
    title: 'Quick Menu'
    attributes:
      cards:
        -
          items:
            -
              description: ''
              price: 1998г.
              link: ''
              target: _blank
              title: 'Начал трудовую деятельность электриком в КФХ "Елена"'
            -
              description: ''
              price: 1999г.
              link: ''
              target: _blank
              title: 'Принят на должность мастера ремонтно-энергетического участка в ОАО "Корммаш"'
            -
              description: ''
              price: 2000г.
              link: ''
              target: _blank
              title: 'Главный энергетик в ОАО "Орловский СК"'
            -
              description: ''
              price: 2003г.
              link: ''
              target: _blank
              title: 'Инженер-проектировщик в ОМУП АГПИ'
            -
              description: ''
              price: 2017г.
              link: ''
              target: _blank
              title: "Принят на должность преподавателя в\_ГБПОУ РО \"СИТ\""
          title: Карьера
        -
          items:
            -
              description: ''
              price: 1999г.
              link: ''
              target: _blank
              title: 'закончил Азово-Черноморскую государственная агроинженерную академию'
            -
              description: ''
              price: 2017г.
              link: ''
              target: _blank
              title: 'дополнительное профессиональное образование в ГБПОУ РО «Новочеркасский колледж промышленных технологий и управления»'
            -
              description: ''
              price: 2018г.
              link: ''
              target: _blank
              title: 'в ФГБОУ ВО «Донской государственный аграрный университет»'
            -
              description: ''
              price: 2019г.
              link: ''
              target: _blank
              title: 'обучение в Региональном отраслевом ресурсном центре подготовки кадров'
          title: Образование
    block:
      extra:
        -
          data-aos: fade-down
  image-8214:
    attributes:
      target: _self
      image: 'gantry-media://new_foto/я1.jpeg'
    block:
      variations: 'nomarginall nopaddingall align-right'
      extra:
        -
          data-aos: fade-up
  position-module-8274:
    title: 'Module Instance'
    attributes:
      module_id: '203'
      key: module-instance
  locations-3441:
    title: 'Location Pins'
    attributes:
      pins:
        -
          phone: 03.05.1977
          icon: 'fa fa-birthday-cake'
          link: ''
          target: _blank
          name: Родился
        -
          phone: 1994-1999
          icon: 'fa fa-book'
          link: ''
          target: _blank
          name: 'Получил высшее образование'
        -
          phone: '1999'
          icon: 'fa fa-wrench'
          link: ''
          target: _blank
          name: 'Начал профессиональную деятельность'
        -
          phone: 30.10.2004
          icon: 'fa fa-heart'
          link: ''
          target: _blank
          name: Женился
        -
          phone: 03.02.2017
          icon: 'fa fa-graduation-cap'
          link: ''
          target: _blank
          name: 'Приступил к преподаванию'
    block:
      variations: 'nomarginall nopaddingall'
  simplecontent-5255:
    title: 'Simple Content'
    attributes:
      class: ''
      title: ''
      items:
        -
          layout: header
          created_date: ''
          content_title: ''
          author: ''
          leading_content: ''
          main_content: 'Занимаясь педагогической деятельностью я понял, что в моей работе самое главное зажечь в глазах учащегося интерес, мотивировать его к обучению, в этом заключается смысл моего педагогического кредо. И именно на этих принципах строится моя работа.'
          readmore_label: ''
          readmore_link: ''
          readmore_class: ''
          readmore_target: _self
          title: 'New item'
    block:
      variations: 'nomarginall nopaddingall'
  flipster-1723:
    title: 'Flipster Cover Flow'
    attributes:
      source: particle
      class: ''
      title: ''
      start: center
      fadein: '400'
      loop: disabled
      autoplay: ''
      pauseonhover: enabled
      style: flat
      spacing: '-0,2'
      click: enabled
      keyboard: enabled
      scrollwheel: disabled
      touch: enabled
      items:
        -
          width: '550'
          accent: accent2
          desc: 'Высшее искусство, которым обладает учитель, - это умение пробудить радость от творческого выражения и получения знаний.'
          title: 'Альберт Эйнштейн'
          image: ''
          buttontext: ''
          buttonlink: ''
          buttontarget: _self
          buttonclass: ''
          name: 'Item 1'
        -
          width: '450'
          accent: white
          desc: 'Всё, что вы видите во мне — это не моё, это ваше. Моё — это то, что я вижу в вас.'
          title: 'Эрих Мария Ремарк'
          image: ''
          buttontext: ''
          buttonlink: ''
          buttontarget: _self
          buttonclass: ''
          name: Центр
        -
          width: '600'
          accent: accent1
          desc: 'И воспитание, и образование нераздельны. Нельзя воспитывать, не передавая знания, всякое же знание действует воспитательно.'
          title: 'Л.Н. Толстой'
          image: ''
          buttontext: ''
          buttonlink: ''
          buttontarget: _self
          buttonclass: ''
          name: 'Item 3'
      article:
        filter:
          categories: ''
          articles: ''
          featured: include
        limit:
          total: '5'
          start: '0'
        sort:
          orderby: publish_up
          ordering: ASC
        display:
          image:
            enabled: intro
          text:
            type: intro
            limit: ''
          title:
            enabled: show
            limit: ''
          link:
            enabled: enabled
            target: _self
  mobile-menu-2576:
    title: 'Mobile Menu'
