version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1666521226
layout:
  top: {  }
  navigation: {  }
  slideshow: {  }
  header: {  }
  above: {  }
  /feature/:
    -
      - 'spacer-6225 15'
      - 'simplecontent-5794 70'
      - 'spacer-5680 14.9'
  showcase: {  }
  utility: {  }
  /container-main/:
    -
      -
        'sidebar 20': {  }
      -
        'mainbar 60': {  }
      -
        'aside 20': {  }
  expanded: {  }
  extension: {  }
  bottom: {  }
  /container-footer/:
    -
      -
        footer: {  }
        copyright: {  }
  offcanvas: {  }
structure:
  top:
    type: section
    inherit:
      outline: '20'
      include:
        - attributes
        - block
        - children
  navigation:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  slideshow:
    type: section
    inherit:
      outline: '20'
      include:
        - attributes
        - block
        - children
  header:
    inherit:
      outline: '20'
      include:
        - attributes
        - block
        - children
  above:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  feature:
    type: section
    attributes:
      boxed: ''
      class: promo
      variations: ''
  showcase:
    type: section
    inherit:
      outline: '20'
      include:
        - attributes
        - block
        - children
  utility:
    type: section
    inherit:
      outline: '20'
      include:
        - attributes
        - block
        - children
  sidebar:
    type: section
    subtype: aside
    inherit:
      outline: '20'
      include:
        - attributes
        - block
        - children
  mainbar:
    type: section
    subtype: main
    title: Main
    inherit:
      outline: '20'
      include:
        - attributes
        - block
        - children
  aside:
    inherit:
      outline: '20'
      include:
        - attributes
        - block
        - children
  container-main:
    attributes:
      boxed: ''
      class: ''
      extra: {  }
  expanded:
    type: section
    inherit:
      outline: '20'
      include:
        - attributes
        - block
        - children
  extension:
    type: section
    inherit:
      outline: '20'
      include:
        - attributes
        - block
        - children
  bottom:
    type: section
    inherit:
      outline: '20'
      include:
        - attributes
        - block
        - children
  footer:
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  copyright:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  container-footer:
    attributes:
      boxed: ''
      class: ''
      extra: {  }
  offcanvas:
    inherit:
      outline: '20'
      include:
        - attributes
        - block
        - children
content:
  simplecontent-5794:
    title: 'Simple Content'
    attributes:
      class: ''
      title: ''
      items:
        -
          layout: header
          created_date: ''
          content_title: ''
          author: ''
          leading_content: 'Считай несчастным тот день и тот час, в которые не усвоил ничего нового и не прибавил к своему образованию. <br />                                                                                                                       Я.А. Коменский'
          main_content: "В последние десятилетия в России наблюдается обновление образования в направлении формирования у студентов ключевых компетенций. Обществу требуется специалист новой формации, активный, творчески мыслящий, готовый к применению знаний на практике\nВремена меняются. Изменяются и студенты. Они более разнообразны по возрасту, этнической принадлежности и целям, чем когда-либо прежде.\nПроцесс обучения — это всегда 50/50 процентов усилий преподавателя и студента. Ведь если вам дали образование, это еще не значит, что вы его получили. Помимо лекций и практических рекомендую всем студентам заниматься внеаудиторно. Самостоятельная работа как раз помогает качественно освоить знания и перевести их в опыт.\nСамостоятельная работа студентов — это любая учебная, чаще внеаудиторная деятельность, в которой студент сам ставит себе цель, выбирает задание и вид работы. А я как преподаватель лишь задаёт рамки поиска, обращаю внимание на нужную методическую литературу и определяю сроки. Основная цель данной страницы, представить необходимые материалы или показать пути их нахождения для  обучения вне стен учебного заведения."
          readmore_label: ''
          readmore_link: ''
          readmore_class: ''
          readmore_target: _self
          title: 'New item'
    block:
      variations: 'nomarginall nopaddingall'
  spacer-5680:
    inherit:
      outline: '21'
      include:
        - attributes
        - block
      particle: spacer-6523
